# Generated by Django 3.1.5 on 2024-05-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
